# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.2.1']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker
      uses: Dockerfile
    - name: Build Docker image
      run: docker-compose build
    - name: Prepare DB
      run: docker-compose run web bundle exec rails db:create && bundle exec rake db:test:prepare RAILS_ENV=test
    - name: Run tests
      run: docker-compose run bundle exec rspec spec
